#!/bin/bash

picom &

polybar example &

nitrogen --restore &

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 2

bspc config focused_border_color "#005fff"

bspc config normal_border_color "#000000"

bspc config top_padding 22

bspc config window_gap 12
